export enum OrderStatus {
    PENDING_PAYMENT = "PENDING_PAYMENT",
    PROCESSING = "PROCESSING",
    PAID = "PAID",
    PAYMENT_FAILED = "PAYMENT_FAILED",
    SHIPPED = "SHIPPED",
    DELIVERED = "DELIVERED",
    CANCELED = "CANCELED",
}